DELETE http://localhost:3001/api/blogs/663b4af80704107886d25ceb
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvbmF0aGFuX3dhbmciLCJpZCI6IjY2M2E3OWEzMjFjNTA3ZjQzZTk3NDI1YiIsImlhdCI6MTcxNTE2MTczMn0.s6dOP7iPgcOL_CJP8PiZEDD02a0ROA75THP5Edxogks