DELETE http://localhost:3001/api/blogs/663d1a2d7801d44a521089b2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvbmF0aGFuX3dhbmciLCJpZCI6IjY2M2E3OWEzMjFjNTA3ZjQzZTk3NDI1YiIsImlhdCI6MTcxNTI4MDUzOH0.uD7TDlmaqUdMEoXRxmUY08nugFwkCSl3yxGyMTzAWaU